apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  template:
    spec:
      containers:
      - name: django
        env:
        $patch: merge 
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DEBUG
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: ALLOWED_HOSTS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key