apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-app
type: Opaque
stringData:
  secret-key: "django-insecure-@8k#n&*xm2!q9r%t^y*u(i(o)p_p+s-hgfdsa123456"
  postgres-password: "postgres123"