apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-app
type: Opaque
stringData:
  secret-key: "your-django-secret-key"
  postgres-password: "postgres-password"
  superuser-username: "admin"
  superuser-email: ""
  superuser-password: "admin"