apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/deployment-base.yaml

patchesStrategicMerge:
- patches/django-env.yaml
- patches/postgres-env.yaml
- patches/s3-env.yaml
- patches/volumes.yaml