apiVersion: v1
kind: Pod
metadata:
  name: postgres-ssl
  namespace: edu-igor-derevnin
  labels:
    purpose: postgres-ssl
spec:
  containers:
  - name: postgres-client
    image: postgres:18-alpine
    command: ["sleep", "infinity"]
    env:
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: postgres
          key: host
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          name: postgres
          key: port
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          name: postgres
          key: name
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: postgres
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres
          key: password
    - name: PGSSLMODE
      value: "require"
    - name: PGSSLROOTCERT
      value: "/etc/postgresql/root.crt"
    volumeMounts:
    - name: postgres-ssl
      mountPath: /etc/postgresql
      readOnly: true
  volumes:
  - name: postgres-ssl
    secret:
      secretName: postgres
      items:
      - key: root.crt
        path: root.crt