apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: edu-igor-derevnin
type: Opaque
stringData:
  secret-key: "django-secret-key"
  superuser-username: "admin"
  superuser-email: ""
  superuser-password: "admin"