apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: edu-igor-derevnin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: harpins/django_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000