apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: edu-igor-derevnin                 
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "edu-igor-derevnin.yc-sirius-dev.pelid.team,localhost,127.0.0.1"
  DJANGO_SETTINGS_MODULE: "webapp.settings"
  
  POSTGRES_PORT: "6432"
  PGSSLMODE: "require"
  PGSSLROOTCERT: "/etc/postgresql/root.crt"
  
  POSTGRES_OPTIONS: "sslmode=require&target_session_attrs=read-write"
  
  AWS_STORAGE_BUCKET_NAME: "edu-igor-derevnin"
  AWS_S3_ENDPOINT_URL: "https://storage.yandexcloud.net"
  AWS_S3_REGION_NAME: "ru-central1"
  STATIC_URL: "https://storage.yandexcloud.net/edu-igor-derevnin/static/"
  MEDIA_URL: "https://storage.yandexcloud.net/edu-igor-derevnin/media/"
  STATICFILES_STORAGE: "storages.backends.s3boto3.S3Boto3Storage"
  DEFAULT_FILE_STORAGE: "storages.backends.s3boto3.S3Boto3Storage"
  
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  SECURE_SSL_REDIRECT: "True"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_BROWSER_XSS_FILTER: "True"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  X_FRAME_OPTIONS: "DENY"
  
  LOG_LEVEL: "INFO"
  DJANGO_LOG_LEVEL: "INFO"